First functional release.

diff --git a/pimpupdate b/pimpupdate
--- a/pimpupdate
+++ b/pimpupdate
@@ -5,10 +5,10 @@
 #If you use printed copys to burn down your house, also not my fault, lose data. not my fault. lose time...not my fault. 
 #However if you like it.
 #VARIABLES DON'T TOUCH UNLESS YOU KNOW WHAT YOU ARE GOING TO BREAK!
-SCRIPT_VERSION=1.0.4
+SCRIPT_VERSION=1.0.5
 PIMP_VERSION=`sed -n '2,2p' /etc/version`
 CURL2='/usr/bin/curl'
-PMUPDATEVERURL="http://hackin.yourshell.net/pmupdate/version"
+PMUPDATEVERURL="http://hackin.yourshell.net/pimpupdate/version"
 CURLARGS="-f -s -S -k"
 PMURL="https://github.com/starlilyth/Linux-PoolManager/archive/master.zip"
 SMURL="https://github.com/starlilyth/Linux-SeedManager/archive/master.zip"
@@ -91,6 +91,12 @@ function doinstall.version() {
 			echo "Gathering files for PiMP $PIMP_VERSION....."
 			download /tmp/poolmanager.zip $PMURL
 			download /tmp/poolmanager.conf.tbz2 http://hackin.yourshell.net/pmupdate/poolmanager.conf.1.4-amd-13.12.tbz2
+			doinstall.pimp
+			;;
+		1.4-amd-14.4 )
+			echo "Gathering files for PiMP $PIMP_VERSION....."
+			download /tmp/poolmanager.zip $PMURL
+			download /tmp/poolmanager.conf.tbz2 http://hackin.yourshell.net/pmupdate/poolmanager.conf.1.4-amd-14.4.tbz2
 			doinstall.pimp
 			;;
 		9.9.9 )
@@ -221,11 +227,12 @@ function doinstall.wicdfix() {
 esac
 }
 function doinstall.smprofiles() {
-echo "Update seedmanager.conf with latest miner profiles (DOES NOT REPLACE YOUR CGMINER.CONF FILES)"
-echo "Note this will reset your active mining profile to scrypt, as well as remove any email notification settings"
-echo "Install updated profiles? Y/N:"
+echo "Update seedmanager.conf with the latest Seedmanager profile?"
+echo "Note this will reset your email notification settings"
+echo "Install updated profile? Y/N:"
 	read SMPROFILES
 	if [ $SMPROFILES == y ]; then
+		/opt/ifmi/smcontrol stop 2&>/dev/null
 	    echo "Backing up old seedmanager.conf to /opt/ifmi/seedmanager.conf.bak"
 	    if [[ -e /opt/ifmi/seedmanager.conf ]]; then
 	    	mv /opt/ifmi/seedmanager.conf /opt/ifmi/seedmanager.conf.bak
@@ -234,11 +241,11 @@ echo "Install updated profiles? Y/N:"
 	    	sleep 2
 	    else echo "No seedmanager.conf found to back up...Continuing..."
 		fi
-		echo "PiMP Updated default algorithm profiles installed...Enjoy!"
+		echo "Updated Seedmanager profile installed...Enjoy!"
 		echo "Remember to reconfigure your email alert settings after using this feature"
 		rm /tmp/seedmanager.conf.tbz2
 		echo "Restarting mining..... (May take 30-45 seconds!)"
-		/etc/init.d/mine start
+		/opt/ifmi/smcontrol start
 		echo "Done..."
 		echo "Script completed! Please report bugs to Sling00 in #PIMP irc.freenode.net"
 		exit 0
@@ -253,6 +260,7 @@ echo "Note this will reset your active mining profile to scrypt, as well as remo
 echo "Install updated profiles? Y/N:"
 	read PMPROFILES
 	if [ $PMPROFILES == y ]; then
+		f.minestop
 	    echo "Backing up old poolmanager.conf to /opt/ifmi/poolmanager.conf.bak"
 	    if [[ -e /opt/ifmi/poolmanager.conf ]]; then
 	    	mv /opt/ifmi/poolmanager.conf /opt/ifmi/poolmanager.conf.bak
@@ -264,9 +272,7 @@ echo "Install updated profiles? Y/N:"
 		echo "PiMP Updated default algorithm profiles installed...Enjoy!"
 		echo "Remember to reconfigure your email alert settings after using this feature"
 		rm /tmp/poolmanager.conf.tbz2
-
-		echo "Restarting mining..... (May take 30-45 seconds!)"
-		/etc/init.d/mine start
+		f.minestart
 		echo "Done..."
 		echo "Script completed! Please report bugs to Sling00 in #PIMP irc.freenode.net"
 		exit 0
@@ -274,9 +280,12 @@ echo "Install updated profiles? Y/N:"
 exit 0
 fi
 }
+function f.minestart() {
+	echo "Restarting mining..... (May take 30-45 seconds!)"
+	/etc/init.d/mine start
+}
 # Mine stop function
-#}
-function minestop() {
+function f.minestop() {
 echo "Stopping mining....."
 /etc/init.d/mine stop
 }
@@ -285,7 +294,7 @@ function doinstall.nodm() {
 $THELINE
 echo "Updating Premine scripts to latest version..."
 echo "Downloading latest nodm.tar from patch site..."
-download /tmp/nodm.tar http://hackin.yourshell.net/nodm.tar
+download /tmp/nodm.tar http://hackin.yourshell.net/nodm/nodm.tar
 echo "Backing up old /etc/init.d/nodm to /root/nodm.bak"
 cp /etc/init.d/nodm /root/nodm.bak
 echo "Extracting new /etc/init.d/nodm....."
@@ -355,30 +364,28 @@ if [ "$UID" -ne 0 ]
   then echo "ERROR: Please run as root"
   else
 $THELINE
-echo -e '\E[00;34m'"\033[1mPoolmanager update & Profile update for PiMP /universal Version $SCRIPT_VERSION\033[0m"
+echo -e '\E[00;34m'"\033[1mPiMPUpdate Version $SCRIPT_VERSION\033[0m"
 echo -e '\E[00;31m'"\033[1mScript by Sling00\033[0m"
 $THELINE
 echo -e '\E[00;31m'"\033[1mNOTE: Installation on BAMT or OTHER OS IS EXPERIMENTAL!\033[0m"
-#sleep 5
 echo -n "Do you wish to continue Enter y/n: "
-	read PMUPDATE_CONTINUE
-	if [ $PMUPDATE_CONTINUE == y ]; then
-		echo "Getting latest version of pmupdate"
-#Is pmupdate up to date?! Updater code below...		
-	echo "Checking if pmupdate script is up to date........"
+	read PMPUPDATE_CONTINUE
+	if [ $PMPUPDATE_CONTINUE == y ]; then
+		echo "Getting latest version of pimpupdate"
+#Is pimpupdate up to date?! Updater code below...		
+	echo "Checking if Pimpupdate is up to date........"
 	if [ $SCRIPT_NEW_VERSION \> $SCRIPT_VERSION ];
 	then
 	echo -n "pmupdate script is out of date! Would you like it to update itself? y/n: "
-	read PMUPDATE_UPDATE
-	if [ $PMUPDATE_UPDATE == y ]; then
+	read PMPUPDATE_UPDATE
+	if [ $PMPUPDATE_UPDATE == y ]; then
 		echo "Getting latest version of updatepm"
-		download /tmp/pmupdate.tar http://hackin.yourshell.net/pmupdate.tar
-		tar xvf /tmp/pmupdate.tar -C /opt/pimp/ > /tmp/pmupdate.log
+		download /tmp/pimpupdate.tar http://hackin.yourshell.net/pimpupdate/pimpupdate.tar
+		tar xvf /tmp/pimpupdate.tar -C /opt/pimp/ > /tmp/pmupdate.log
 		echo "Update completed. Please rerun this script to continue."
-		rm /tmp/pmupdate.tar
+		rm /tmp/pimpupdate.tar
 		exit 0
 	else
-
 	echo "not updating...Continue at your own risk....."
 	$THELINE
 fi
@@ -387,18 +394,9 @@ fi
 	$THELINE
 	pimpmenu
 	fi
-    
-fi
 #Work begins below
-#Installer Function-Pimp
-
-#else
-#$THELINE
+else
+	echo "Error: Not updating because the user didn't answer y when prompted."
+	exit 1
 fi
-
-#if [[ sed -n '2,2p' /etc/version ]] 
-
-#else
-#	echo "Error: Not updating because the user didn't answer y when prompted."
-#	exit 1
-#fi
+fi
