Change versioning for pimpmenu

diff --git a/pimpupdate b/pimpupdate
--- a/pimpupdate
+++ b/pimpupdate
@@ -1003,7 +1003,7 @@ fi
 fi
 }
 
-function pimpmenu16() {
+function pimpmenu155() {
 local PMSELECT_1="1. Update Poolmanager"
 local PMSELECT_2="2. Reinstall Poolmanager profiles (Use if you deleted poolmanager.conf)"
 local PMSELECT_3="3. Update Seedmanager"
@@ -1281,45 +1281,27 @@ fi
 }
 
 function pimpmenu() {
-PIMP_VERSION2=`echo $PIMPVERSION | grep -o '1.4.1'`
-	   if [[ `sed -n '2,2p' /etc/version  | grep -c 1.4.1-amd` = 1 ]];
-		then
-    		pimpmenu141
-    	elif [[ `sed -n '2,2p' /etc/version  | grep -c 1.4.2-amd` = 1 ]];
-    	then
-    		pimpmenu141
-    	elif [[ `sed -n '2,2p' /etc/version  | grep -c 1.5.2-amd` = 1 ]];
-    	then
-    		pimpmenu141
-    	elif [[ `sed -n '2,2p' /etc/version  | grep -c 1.4.3-amd` = 1 ]];
-    	then
-    		pimpmenu152
-    	elif [[ `sed -n '2,2p' /etc/version  | grep -c 1.5.3-amd` = 1 ]];
-    	then
-    		pimpmenu152
-    	elif [[ `sed -n '2,2p' /etc/version  | grep -c 1.4.4-amd` = 1 ]];
-    	then
-    		pimpmenu16
-    	elif [[ `sed -n '2,2p' /etc/version  | grep -c 1.5.4-amd` = 1 ]];
-    	then
-    		pimpmenu16
-    	elif [[ `sed -n '2,2p' /etc/version  | grep -c 1.5.5-amd` = 1 ]];
-    	then
-    		pimpmenu16
-    	elif [[ `sed -n '2,2p' /etc/version  | grep -c 1.6.0-amd` = 1 ]];
-    	then
-    		pimpmenu16
-    	elif [[ `sed -n '2,2p' /etc/version  | grep -c 1.5.51-amd` = 1 ]];
-    	then
-    		pimpmenu156
-    	elif [[ `sed -n '2,2p' /etc/version  | grep -c 1.5.6-amd` = 1 ]];
-    	then
-    		pimpmenu156
-    	else
+PIMP_VERSION2=`sed -n '2,2p' /etc/version | cut -d "-" -f 1,2`
+	   	case $PIMP_VERSION2 in
+	   	1.3.1-amd | 1.4-amd )
 			pimpmenu14
-	fi
+	   	1.4.2-amd | 1.5.2-amd )
+			pimpmenu141
+		;;
+		1.4.3-amd | 1.5.3-amd )
+			pimpmenu152
+		;;
+		1.4.4-amd | 1.5.4-amd | 1.5.5-amd )
+			pimpmenu155
+		;;
+		1.5.51 | 1.5.6-amd )
+			pimpmenu156
+		;;
+		* )
+		echo "Error: This version is not yet supported by pimpupdate."
+		exit 1
+		;;
 }
-
 function f.updatepimpupdate() {
 if [ -z "$1" ]; then 
 	echo -n "Do you wish to continue to the main menu Enter y/n: "
@@ -1386,45 +1368,35 @@ $THELINE
 #Additions below
 #Do we have an argument?
 if [ -z "$1" ]; then
-f.updatepimpupdate
-
+	f.updatepimpupdate
 fi
 
 if [ ! -z "$1" ]; then #If arg
-	 	case $1 in
-		1 )
-		doinstall.version
-		;;
-		2 )
-		doinstall.pmprofiles
-		;;
-		3 )
-		doinstall.seedmanager
-		;;
-		4 )
-		doinstall.smprofiles
-		;;
-		5 ) 
-		clear
-		f.minermenu
-		;;
-		6 ) 
-		doinstall.promptfix
-		;;
-		? )
-		echo "Valid arguments:" 
-		;;
+	case $1 in
+	1 )
+	doinstall.version
+	;;
+	2 )
+	doinstall.pmprofiles
+	;;
+	3 )
+	doinstall.seedmanager
+	;;
+	4 )
+	doinstall.smprofiles
+	;;
+	5 ) 
+	clear
+	f.minermenu
+	;;
+	6 ) 
+	doinstall.promptfix
+	;;
+	update ) 
+	f.pimpupdateupdate
+	;;
+	* )
+	echo "Valid command line arguments:" 
+	;;
 	esac
-#if [ $1 = "?" ]; then
-#	echo "Valid arguments:"
-#fi
-
-#if [ $1 = "1" ]; then
-#	doinstall.version
-#fi
-#if [ $1 = "update" ]; then
-#	f.updatepimpupdate
-#fi
 fi 
-#endif arg
-	
